# Generated by Django 4.2.16 on 2024-11-20 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=100, verbose_name='书籍名')),
                ('authors', models.CharField(default=' ', max_length=64, verbose_name='作者')),
                ('publisher', models.CharField(default=' ', max_length=254, verbose_name='出版社')),
                ('description', models.CharField(default=' ', max_length=1000, verbose_name='书籍简介')),
                ('image', models.ImageField(upload_to='book/images/', verbose_name='书籍封面')),
                ('url', models.URLField(blank=True, verbose_name='书籍资源链接')),
            ],
            options={
                'verbose_name': '图书管理',
                'verbose_name_plural': '书籍列表',
            },
        ),
        migrations.CreateModel(
            name='Review2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('watchAgain', models.BooleanField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
